apiVersion: v1
kind: Service
metadata:
  name: face-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: face-service
    tier: datascience
  ports:
    - port: 80
      targetPort: 3000