version: "3"
services:
  facedetector:
    build:
      context: models/facedetector/
      dockerfile: Dockerfile
    ports:
      - 8500:8080
    restart: unless-stopped
  fingerprinter:
    image: tensorflow/serving
    ports:
      - 8501:8501
    volumes:
      - ./models/fingerprinter/models/11:/models/fingerprinter/1
    environment:
      - MODEL_NAME=fingerprinter
    restart: unless-stopped

  comparator:
    build:
      context: models/comparator/
      dockerfile: Dockerfile
    ports:
      - 8502:8080
    environment:
      - FACE_SERVICE_URL=http://faceservice:3000/api/v1/faces
      - FINGERPRINT_THRESHOLD="1.7"
      - FINGERPRINT_SHAPE="(64, 64, 1)"
    env_file:
      - database_config.env
    depends_on:
      - faceservice
    restart: unless-stopped

  faceservice:
    build:
      context: api/face-service/
      dockerfile: Dockerfile
    ports:
      - 8503:3000
    environment:
      - IMAGE_PROCESSOR_URL=http://imageprocessor:8080/api/v1/fingerprint
      - COMPARATOR_URL=http://comparator:8080/v1/models/comparator:addFace
    env_file:
      - database_config.env
    depends_on:
      - imageprocessor
    restart: unless-stopped

  gateway:
    build:
      context: api/gateway/
      dockerfile: Dockerfile
    ports:
      - 8504:3000
    environment:
      - FACE_SERVICE_URL=http://faceservice:8080/
      - VIDEO_DOWNSCALER_URL=http://videodownscaler:8080/
    env_file:
      - database_config.env
    restart: unless-stopped

  videodownscaler:
    build:
      context: api/video-downscaler/
      dockerfile: Dockerfile
    ports:
      - 8505:8080
    restart: unless-stopped

  imageprocessor:
    build:
      context: api/image-processor/
      dockerfile: Dockerfile
    ports:
      - 8506:8080
    environment:
      - FACEDETECTOR_URL=http://facedetector:8080/v1/models/facedetector:predict
      - FINGERPRINTER_URL=http://fingerprinter:8501/v1/models/fingerprinter:predict
      - COMPARATOR_URL=http://comparator:8080/v1/models/comparator:predict
      - FACE_SERVICE_URL=http://faceservice:3000/api/v1/faces
    depends_on:
      - facedetector
      - fingerprinter
    restart: unless-stopped

#  dashboard:
#    build:
#      context: ui/user-dashboard
#      dockerfile: Dockerfile
#    ports:
#      - 4000:80

