version: '3'
services:
  facedetector:
    build:
      context: facedetector/
      dockerfile: Dockerfile
    ports:
      - 8500:8080
  fingerprinter:
    image: tensorflow/serving
    ports:
      - 8501:8501
    volumes:
      - /Users/akassharjun/Code/SDGP/speculo/fingerprinter/models:/models/fingerprinter
    environment:
      - MODEL_NAME=fingerprinter

      