version: '3'
services:
  facedetector:
    image: tensorflow/serving
    ports:
      - 8500:8501
    volumes:
      - /Users/akassharjun/Code/SDGP/speculo/facedetector/yoloface/model-weights:/models/facedetector
    environment:
      - MODEL_NAME=facedetector
  fingerprinter:
    image: tensorflow/serving
    ports:
      - 8501:8501
    volumes:
      - /Users/akassharjun/Code/SDGP/speculo/fingerprinter/models:/models/fingerprinter
    environment:
      - MODEL_NAME=fingerprinter

      