version: '3'
services:
  facedetector:
    build:
      context: facedetector/
      dockerfile: Dockerfile
    ports:
      - 8500:8080
  fingerprinter:
    image: tensorflow/serving
    ports:
      - 8501:8501
    volumes:
      - ./fingerprinter/models:/models/fingerprinter
    environment:
      - MODEL_NAME=fingerprinter
  comparator:
    build:
      context: api/comparator/
      dockerfile: Dockerfile
    ports:
      - 8502:8080
  postprocessor:
    build:
      context: api/postprocessor/
      dockerfile: Dockerfile
    ports:
      - 8503:8080
    environment:
      - FACEDETECTOR_URL=http://facedetector:8080/v1/models/facedetector:predict
      - FINGERPRINTER_URL=http://fingerprinter:8501/v1/models/fingerprinter:predict
  listingservice:
    build:
      context: api/listing-service/
      dockerfile: Dockerfile
    ports:
      - 8504:8080