version: '3'
services:
  facedetector:
    build:
      context: facedetector/
      dockerfile: Dockerfile
    ports:
      - 8500:8080
  fingerprinter:
    image: tensorflow/serving
    ports:
      - 8501:8501
    volumes:
      - ./fingerprinter/models:/models/fingerprinter
    environment:
      - MODEL_NAME=fingerprinter
  comparator:
    build:
      context: api/matrix-matcher/
      dockerfile: Dockerfile
    ports:
      - 8502:8000