version: "3"
services:
  facedetector:
    build:
      context: models/facedetector/
      dockerfile: Dockerfile
    ports:
      - 8500:8080
  fingerprinter:
    image: tensorflow/serving
    ports:
      - 8501:8501
    volumes:
      - ./models/fingerprinter/models:/models/fingerprinter
    environment:
      - MODEL_NAME=fingerprinter
  comparator:
    build:
      context: models/comparator/
      dockerfile: Dockerfile
    ports:
      - 8502:8080
    environment:
      - FACE_SERVICE_URL=http://faceservice:8080/api/v1/faces
    env_file:
      - database_config.env
  faceservice:
    build:
      context: api/face-service/
      dockerfile: Dockerfile
    ports:
      - 8503:8080
    environment:
      - FACEDETECTOR_URL=http://facedetector:8080/v1/models/facedetector:predict
      - FINGERPRINTER_URL=http://fingerprinter:8501/v1/models/fingerprinter:predict
    env_file:
      - database_config.env
  gateway:
    build:
      context: api/gateway/
      dockerfile: Dockerfile
    ports:
      - 8504:3000
    environment:
      - FACE_SERVICE_URL=http://faceservice:8080/
      - IMAGE_PROCESSOR_URL=http://imageprocessor:8080/
    env_file:
      - database_config.env
  videodownscaler:
    build:
      context: api/video-downscaler/
      dockerfile: Dockerfile
    ports:
      - 8505:8080
  imageprocessor:
    build:
      context: api/image-processor/
      dockerfile: Dockerfile
    ports:
      - 8506:8080
    environment:
      - FACEDETECTOR_URL=http://facedetector:8080/v1/models/facedetector:predict
      - FINGERPRINTER_URL=http://fingerprinter:8501/v1/models/fingerprinter:predict
      - COMPARATOR_PREDICT_URL=http://comparator:8080/v1/models/comparator:predict
      - COMPARATOR_ADD_URL=http://comparator:8080/v1/models/comparator:addFace
  dashboard:
    build:
      context: ui/user-dashboard/DockerFile
      dockerfile: Dockerfile
    ports:
      - 4000:80