apiVersion: v1
kind: Service
metadata:
  name: image-processor-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: image-processor
    tier: backend
  ports:
    - port: 80
      targetPort: 8080