apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: image-processor
  template:
    metadata:
      labels:
        component: image-processor
        tier: backend
    spec:
      containers:
        - name: image-processor
          image: docker.pkg.github.com/mrsupiri/speculo/image-processor:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: FACE_SERVICE_URL
              value: http://face-service-cluster-ip-service/api/v1/faces
            - name: COMPARATOR_URL
              value: http://facecomparator-cluster-ip-service/v1/models/facecomparator:predict
            - name: FACEDETECTOR_URL
              value: http://facedetector-cluster-ip-service/v1/models/facedetector:predict
            - name: FINGERPRINTER_URL
              value: http://fingerprinter-cluster-ip-service/v1/models/fingerprinter:predict
