apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: image-processor
  template:
    metadata:
      labels:
        component: image-processor
        tier: datascience
    spec:
      containers:
        - name: image-processor
          image: docker.pkg.github.com/mrsupiri/speculo/image-processor:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: FACE_SERVICE_URL
              value: http://face-service-cluster-ip-service:80/
            - name: COMPARATOR_URL
              value: http://facecomparator-cluster-ip-service:80/
            - name: FACEDETECTOR_URL
              value: http://facedetector-cluster-ip-service:80/
            - name: FINGERPRINTER_URL
              value: http://fingerprinter-cluster-ip-service:80/
