apiVersion: v1
kind: Service
metadata:
  name: video-downscaler-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: video-downscaler
    tier: backend
  ports:
    - port: 80
      targetPort: 8080