version: 1
update_configs:
  # Keep the front end libraries updated

  ## user dashboard
  - package_manager: "javascript"
    directory: "/ui/user-dashboard/"
    update_schedule: "live"
    default_assignees:
      - "DinDev3"
    default_labels:
      - "dependencies"
      - "dependabot"
      - "security"

  # Keeping the microservices dependencies updated

  ## api gateway
  - package_manager: "javascript"
    directory: "/api/gateway/"
    update_schedule: "live"
    default_assignees:
      - "akassharjun"
    default_labels:
      - "dependencies"
      - "dependabot"
      - "security"
      
    ## api face service
  - package_manager: "javascript"
    directory: "/api/face-service/"
    update_schedule: "live"
    default_assignees:
      - "akassharjun"
    default_labels:
      - "dependencies"
      - "dependabot"
      - "security"

  ## image postprocessor
  - package_manager: "python"
    directory: "/api/image-processor/"
    update_schedule: "live"
    default_assignees:
      - "akassharjun"
    default_labels:
      - "dependencies"
      - "dependabot"
      - "security"

  ## image facecomparator
  - package_manager: "python"
    directory: "models/facecomparator/"
    update_schedule: "live"
    default_assignees:
      - "mrsupiri"
    default_labels:
      - "dependencies"
      - "dependabot"
      - "security"

  ## facedetector
  - package_manager: "python"
    directory: "models/facedetector/"
    update_schedule: "live"
    default_assignees:
      - "mrsupiri"
    default_labels:
      - "dependencies"
      - "dependabot"
      - "security"

  ## fingerprinter
  - package_manager: "python"
    directory: "models/fingerprinter/"
    update_schedule: "live"
    default_assignees:
      - "mrsupiri"
    default_labels:
      - "dependencies"
      - "dependabot"
      - "security"
