apiVersion: v1
kind: Service
metadata:
  name: fingerprinter-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: fingerprinter
    tier: datascience
  ports:
    - port: 80
      targetPort: 8501