apiVersion: apps/v1
kind: Deployment
metadata:
  name: fingerprinter-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: fingerprinter
  template:
    metadata:
      labels:
        component: fingerprinter
        tier: datascience
    spec:
      containers:
        - name: fingerprinter
          image: docker.pkg.github.com/mrsupiri/speculo/fingerprinter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MODEL_NAME
              value: fingerprinter
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 200m