apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fingerprinter-pod-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fingerprinter-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80