apiVersion: v1
kind: Service
metadata:
  name: facedetector-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: facedetector
    tier: datascience
  ports:
    - port: 80
      targetPort: 8080