name: Pull Request Testing

on:
  pull_request:
    types: [assigned, opened]
  pull_request_review:
    types: [submitted, edited]

jobs:
  user-dashboard-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ui/user-dashboard
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
  data-science-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: models
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install python package manager
        run: python -m pip install --upgrade pip
      - name: Install facecomparator dependencies
        run: pip install -r facecomparator/requirements.txt
      - name: Install facedetector dependencies
        run: pip install -r facedetector/requirements.txt
      - name: Install fingerprinter dependencies
        run: pip install -r fingerprinter/requirements.txt
      - name: Downloading and extracting models
        run: |
          curl -sL https://cdn.iconicto.com/Speculo/fingerprinter/Model-v12.h5 -o fingerprinter/models/12/Model-v12.h5
          mkdir -p facedetector/model-weights/
          curl -sL https://cdn.iconicto.com/Speculo/facedetector/yoloface/model-weights/YOLO_Face.h5 -o facedetector/model-weights/YOLO_Face.h5

      - name: Cache evaluation data set
        uses: actions/cache@v1
        env:
          cache-name: evaluation-data-set
        with:
          path: ./dataset_evaluate
          key: evaluation-data-set-cache
          restore-keys: |
            evaluation-data-set-cache

      - name: Downloading and extracting the dataset
        run: |
          curl -sL http://www-prima.inrialpes.fr/perso/Gourier/Faces/HeadPoseImageDatabase.tar.gz -o dataset_evaluate.tar.gz
          mkdir dataset_evaluate
          tar -xvf dataset_evaluate.tar.gz -C dataset_evaluate
      - name: Testing All 3 Models
        run: python3 model_tester.py
        env:
          CI: true
  smoke-testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Exporting secrets
      run: echo ${{secrets.database_config}} >> database_config.env
    - name: Building Containers
      run: docker-compose build --pull
