name: Pull Request Testing

on: [pull_request]

jobs:
  user-dashboard-testing:
    runs-on: ubuntu-latest
    env:
      working-directory: ui/user-dashboard

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
  data-science-testing:
    runs-on: ubuntu-latest
    env:
      working-directory: models

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install python package manager
        run: python -m pip install --upgrade
      - name: Install facecomparator dependencies
        run: pip -r facecomparator/requirements.txt
      - name: Install facedetector dependencies
        run: pip -r facedetector/requirements.txt
      - name: Install fingerprinter dependencies
        run: pip -r fingerprinter/requirements.txt
      - name: Downloading and extracting models
        run: |
          curl -sL https://cdn.iconicto.com/Speculo/fingerprinter/Model-v12.h5 -o fingerprinter/models/12
          curl -sL https://cdn.iconicto.com/Speculo/facedetector/yoloface/model-weights/YOLO_Face.h5 -o facedetector/model-weights/YOLO_Face.h5
      - name: Downloading and extracting the dataset
        run: |
          curl -sL http://www-prima.inrialpes.fr/perso/Gourier/Faces/HeadPoseImageDatabase.tar.gz -o dataset_evaluate.tar.gz
          mkdir dataset_evaluate
          tar -xvf dataset_evaluate.tar.gz -C dataset_evaluate
      - name: Benchmark the model
        run: python3 model_tester.py